projectTitle = "Team Voided Template"
modId = "template"
githubRepo = "Teamvoided/TeamVoidedTemplateMod"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "brokenfuse", "theendercore" ]
majorMinecraftVersion = "1.20"
minecraftVersion = "1.20.4"
fabricLoaderVersion = "0.15.10"
fabricApiVersion = "0.97.0+1.20.4"
fabricLangKotlinVersion = "1.10.19+kotlin.1.9.23"
license = "MIT"
modules = [ ]

[mappings]
    # You have 7 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    # CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "QUILT"
    version = "1.20.4+build.3"